/*

The MIT License (MIT)

Copyright (c) 2014 Guillermo Rauch


Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. Socket.IO v2.1.1
 (c) 2014-2018 Guillermo Rauch
 Released under the MIT License.
 https://mths.be/utf8js v2.1.2 by @mathias */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(n){var f=0;return function(){return f<n.length?{done:!1,value:n[f++]}:{done:!0}}};$jscomp.arrayIterator=function(n){return{next:$jscomp.arrayIteratorImpl(n)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(n,f,e){if(n==Array.prototype||n==Object.prototype)return n;n[f]=e.value;return n};$jscomp.getGlobal=function(n){n=["object"==typeof globalThis&&globalThis,n,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var f=0;f<n.length;++f){var e=n[f];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(n,f){var e=$jscomp.propertyToPolyfillSymbol[f];if(null==e)return n[f];e=n[e];return void 0!==e?e:n[f]};
$jscomp.polyfill=function(n,f,e,c){f&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(n,f,e,c):$jscomp.polyfillUnisolated(n,f,e,c))};$jscomp.polyfillUnisolated=function(n,f,e,c){e=$jscomp.global;n=n.split(".");for(c=0;c<n.length-1;c++){var d=n[c];if(!(d in e))return;e=e[d]}n=n[n.length-1];c=e[n];f=f(c);f!=c&&null!=f&&$jscomp.defineProperty(e,n,{configurable:!0,writable:!0,value:f})};
$jscomp.polyfillIsolated=function(n,f,e,c){var d=n.split(".");n=1===d.length;c=d[0];c=!n&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<d.length-1;g++){var l=d[g];if(!(l in c))return;c=c[l]}d=d[d.length-1];e=$jscomp.IS_SYMBOL_NATIVE&&"es6"===e?c[d]:null;f=f(e);null!=f&&(n?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:f}):f!==e&&(void 0===$jscomp.propertyToPolyfillSymbol[d]&&(e=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+e+"$"+d),$jscomp.defineProperty(c,$jscomp.propertyToPolyfillSymbol[d],{configurable:!0,writable:!0,value:f})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(n){if(n)return n;var f=function(g,l){this.$jscomp$symbol$id_=g;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:l})};f.prototype.toString=function(){return this.$jscomp$symbol$id_};var e="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",c=0,d=function(g){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new f(e+(g||"")+"_"+c++,g)};return d},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(n){if(n)return n;n=Symbol("Symbol.iterator");for(var f="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),e=0;e<f.length;e++){var c=$jscomp.global[f[e]];"function"===typeof c&&"function"!=typeof c.prototype[n]&&$jscomp.defineProperty(c.prototype,n,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return n},"es6",
"es3");$jscomp.iteratorPrototype=function(n){n={next:n};n[Symbol.iterator]=function(){return this};return n};$jscomp.iteratorFromArray=function(n,f){n instanceof String&&(n+="");var e=0,c=!1,d={next:function(){if(!c&&e<n.length){var g=e++;return{value:f(g,n[g]),done:!1}}c=!0;return{done:!0,value:void 0}}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.keys",function(n){return n?n:function(){return $jscomp.iteratorFromArray(this,function(f){return f})}},"es6","es3");
(function(n,f){"object"===typeof exports&&"object"===typeof module?module.exports=f():"function"===typeof define&&define.amd?define([],f):"object"===typeof exports?exports.io=f():n.io=f()})(this,function(){return function(n){function f(c){if(e[c])return e[c].exports;var d=e[c]={exports:{},id:c,loaded:!1};n[c].call(d.exports,d,d.exports,f);d.loaded=!0;return d.exports}var e={};f.m=n;f.c=e;f.p="";return f(0)}([function(n,f,e){function c(t,r){"object"===("undefined"===typeof t?"undefined":d(t))&&(r=
t,t=void 0);r=r||{};t=g(t,null,r.path||"/socket.io");var h=t.source,a=t.id,b=t.path;b=u[a]&&b in u[a].nsps;r.forceNew||r["force new connection"]||!1===r.multiplex||b?(v("ignoring socket cache for %s",h),h=p(h,r)):(u[a]||(v("new io instance for %s",h),u[a]=p(h,r)),h=u[a]);t.query&&!r.query&&(r.query=t.query);return h.socket(t.path,r)}var d="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&&"function"===typeof Symbol&&t.constructor===Symbol&&
t!==Symbol.prototype?"symbol":typeof t},g=e(1),l=e(7),p=e(12),v=e(3)("socket.io-client");n.exports=f=c;var u=f.managers={};f.protocol=l.protocol;f.connect=c;f.Manager=e(12);f.Socket=e(37)},function(n,f,e){(function(c){var d=e(2),g=e(3)("socket.io-client:url");n.exports=function(l,p,v){var u=l;p=p||c.location;null==l&&(l=p.protocol+"//"+p.host);"string"===typeof l&&("/"===l.charAt(0)&&(l="/"===l.charAt(1)?p.protocol+l:p.host+l),/^(https?|wss?):\/\//.test(l)||(g("protocol-less url %s",l),l="undefined"!==
typeof p?p.protocol+"//"+l:"https://"+l),g("parse %s",l),u=d(l));u.port||(/^(http|ws)$/.test(u.protocol)?u.port="80":/^(http|ws)s$/.test(u.protocol)&&(u.port="443"));u.path=u.path||"/";l=-1!==u.host.indexOf(":")?"["+u.host+"]":u.host;u.id=u.protocol+"://"+l+":"+u.port+v;u.href=u.protocol+"://"+l+(p&&p.port===u.port?"":":"+u.port);return u}}).call(f,function(){return this}())},function(n,f){var e=/^(?:(?![^:@]+:[^:@\/]*@)(http|https|ws|wss):\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?((?:[a-f0-9]{0,4}:){2,7}[a-f0-9]{0,4}|[^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,
c="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");n.exports=function(d){var g=d,l=d.indexOf("["),p=d.indexOf("]");-1!=l&&-1!=p&&(d=d.substring(0,l)+d.substring(l,p).replace(/:/g,";")+d.substring(p,d.length));d=e.exec(d||"");for(var v={},u=14;u--;)v[c[u]]=d[u]||"";-1!=l&&-1!=p&&(v.source=g,v.host=v.host.substring(1,v.host.length-1).replace(/;/g,":"),v.authority=v.authority.replace("[","").replace("]","").replace(/;/g,":"),v.ipv6uri=
!0);return v}},function(n,f,e){(function(c){function d(){try{var p=f.storage.debug}catch(v){}!p&&"undefined"!==typeof c&&"env"in c&&(p=c.env.DEBUG);return p}f=n.exports=e(5);f.log=function(){return"object"===typeof console&&console.log&&Function.prototype.apply.call(console.log,console,arguments)};f.formatArgs=function(p){var v=this.useColors;p[0]=(v?"%c":"")+this.namespace+(v?" %c":" ")+p[0]+(v?"%c ":" ")+"+"+f.humanize(this.diff);if(v){v="color: "+this.color;p.splice(1,0,v,"color: inherit");var u=
0,t=0;p[0].replace(/%[a-zA-Z%]/g,function(r){"%%"!==r&&(u++,"%c"===r&&(t=u))});p.splice(t,0,v)}};f.save=function(p){try{null==p?f.storage.removeItem("debug"):f.storage.debug=p}catch(v){}};f.load=d;f.useColors=function(){return"undefined"!==typeof window&&window.process&&"renderer"===window.process.type?!0:"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/(edge|trident)\/(\d+)/)?!1:"undefined"!==typeof document&&document.documentElement&&document.documentElement.style&&
document.documentElement.style.WebkitAppearance||"undefined"!==typeof window&&window.console&&(window.console.firebug||window.console.exception&&window.console.table)||"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/firefox\/(\d+)/)&&31<=parseInt(RegExp.$1,10)||"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/applewebkit\/(\d+)/)};var g=f;if("undefined"!=typeof chrome&&"undefined"!=typeof chrome.storage)var l=
chrome.storage.local;else a:{try{l=window.localStorage;break a}catch(p){}l=void 0}g.storage=l;f.colors="#0000CC #0000FF #0033CC #0033FF #0066CC #0066FF #0099CC #0099FF #00CC00 #00CC33 #00CC66 #00CC99 #00CCCC #00CCFF #3300CC #3300FF #3333CC #3333FF #3366CC #3366FF #3399CC #3399FF #33CC00 #33CC33 #33CC66 #33CC99 #33CCCC #33CCFF #6600CC #6600FF #6633CC #6633FF #66CC00 #66CC33 #9900CC #9900FF #9933CC #9933FF #99CC00 #99CC33 #CC0000 #CC0033 #CC0066 #CC0099 #CC00CC #CC00FF #CC3300 #CC3333 #CC3366 #CC3399 #CC33CC #CC33FF #CC6600 #CC6633 #CC9900 #CC9933 #CCCC00 #CCCC33 #FF0000 #FF0033 #FF0066 #FF0099 #FF00CC #FF00FF #FF3300 #FF3333 #FF3366 #FF3399 #FF33CC #FF33FF #FF6600 #FF6633 #FF9900 #FF9933 #FFCC00 #FFCC33".split(" ");
f.formatters.j=function(p){try{return JSON.stringify(p)}catch(v){return"[UnexpectedJSONParseError]: "+v.message}};f.enable(d())}).call(f,e(4))},function(n,f){function e(){throw Error("setTimeout has not been defined");}function c(){throw Error("clearTimeout has not been defined");}function d(m){if(t===setTimeout)return setTimeout(m,0);if((t===e||!t)&&setTimeout)return t=setTimeout,setTimeout(m,0);try{return t(m,0)}catch(w){try{return t.call(null,m,0)}catch(B){return t.call(this,m,0)}}}function g(m){if(r===
clearTimeout)return clearTimeout(m);if((r===c||!r)&&clearTimeout)return r=clearTimeout,clearTimeout(m);try{return r(m)}catch(w){try{return r.call(null,m)}catch(B){return r.call(this,m)}}}function l(){a&&b&&(a=!1,b.length?h=b.concat(h):k=-1,h.length&&p())}function p(){if(!a){var m=d(l);a=!0;for(var w=h.length;w;){b=h;for(h=[];++k<w;)b&&b[k].run();k=-1;w=h.length}b=null;a=!1;g(m)}}function v(m,w){this.fun=m;this.array=w}function u(){}n=n.exports={};try{var t="function"===typeof setTimeout?setTimeout:
e}catch(m){t=e}try{var r="function"===typeof clearTimeout?clearTimeout:c}catch(m){r=c}var h=[],a=!1,b,k=-1;n.nextTick=function(m){var w=Array(arguments.length-1);if(1<arguments.length)for(var B=1;B<arguments.length;B++)w[B-1]=arguments[B];h.push(new v(m,w));1!==h.length||a||d(p)};v.prototype.run=function(){this.fun.apply(null,this.array)};n.title="browser";n.browser=!0;n.env={};n.argv=[];n.version="";n.versions={};n.on=u;n.addListener=u;n.once=u;n.off=u;n.removeListener=u;n.removeAllListeners=u;n.emit=
u;n.prependListener=u;n.prependOnceListener=u;n.listeners=function(m){return[]};n.binding=function(m){throw Error("process.binding is not supported");};n.cwd=function(){return"/"};n.chdir=function(m){throw Error("process.chdir is not supported");};n.umask=function(){return 0}},function(n,f,e){function c(l){var p=0,v;for(v in l)p=(p<<5)-p+l.charCodeAt(v),p|=0;return f.colors[Math.abs(p)%f.colors.length]}function d(l){function p(){if(p.enabled){var u=+new Date;p.diff=u-(v||u);p.prev=v;v=p.curr=u;var t=
Array(arguments.length);for(u=0;u<t.length;u++)t[u]=arguments[u];t[0]=f.coerce(t[0]);"string"!==typeof t[0]&&t.unshift("%O");var r=0;t[0]=t[0].replace(/%([a-zA-Z%])/g,function(h,a){if("%%"===h)return h;r++;a=f.formatters[a];"function"===typeof a&&(h=a.call(p,t[r]),t.splice(r,1),r--);return h});f.formatArgs.call(p,t);(p.log||f.log||console.log.bind(console)).apply(p,t)}}var v;p.namespace=l;p.enabled=f.enabled(l);p.useColors=f.useColors();p.color=c(l);p.destroy=g;"function"===typeof f.init&&f.init(p);
f.instances.push(p);return p}function g(){var l=f.instances.indexOf(this);return-1!==l?(f.instances.splice(l,1),!0):!1}f=n.exports=d.debug=d["default"]=d;f.coerce=function(l){return l instanceof Error?l.stack||l.message:l};f.disable=function(){f.enable("")};f.enable=function(l){f.save(l);f.names=[];f.skips=[];var p,v=("string"===typeof l?l:"").split(/[\s,]+/),u=v.length;for(p=0;p<u;p++)v[p]&&(l=v[p].replace(/\*/g,".*?"),"-"===l[0]?f.skips.push(new RegExp("^"+l.substr(1)+"$")):f.names.push(new RegExp("^"+
l+"$")));for(p=0;p<f.instances.length;p++)l=f.instances[p],l.enabled=f.enabled(l.namespace)};f.enabled=function(l){if("*"===l[l.length-1])return!0;var p;var v=0;for(p=f.skips.length;v<p;v++)if(f.skips[v].test(l))return!1;v=0;for(p=f.names.length;v<p;v++)if(f.names[v].test(l))return!0;return!1};f.humanize=e(6);f.instances=[];f.names=[];f.skips=[];f.formatters={}},function(n,f){function e(d){d=String(d);if(!(100<d.length)&&(d=/^((?:\d+)?\.?\d+) *(milliseconds?|msecs?|ms|seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|years?|yrs?|y)?$/i.exec(d))){var g=
parseFloat(d[1]);switch((d[2]||"ms").toLowerCase()){case "years":case "year":case "yrs":case "yr":case "y":return 315576E5*g;case "days":case "day":case "d":return 864E5*g;case "hours":case "hour":case "hrs":case "hr":case "h":return 36E5*g;case "minutes":case "minute":case "mins":case "min":case "m":return 6E4*g;case "seconds":case "second":case "secs":case "sec":case "s":return 1E3*g;case "milliseconds":case "millisecond":case "msecs":case "msec":case "ms":return g}}}function c(d,g,l){if(!(d<g))return d<
1.5*g?Math.floor(d/g)+" "+l:Math.ceil(d/g)+" "+l+"s"}n.exports=function(d,g){g=g||{};var l=typeof d;if("string"===l&&0<d.length)return e(d);if("number"===l&&!1===isNaN(d))return g.long?c(d,864E5,"day")||c(d,36E5,"hour")||c(d,6E4,"minute")||c(d,1E3,"second")||d+" ms":864E5<=d?Math.round(d/864E5)+"d":36E5<=d?Math.round(d/36E5)+"h":6E4<=d?Math.round(d/6E4)+"m":1E3<=d?Math.round(d/1E3)+"s":d+"ms";throw Error("val is not a non-empty string or a valid number. val="+JSON.stringify(d));}},function(n,f,e){function c(){}
function d(a){var b=""+a.type;if(f.BINARY_EVENT===a.type||f.BINARY_ACK===a.type)b+=a.attachments+"-";a.nsp&&"/"!==a.nsp&&(b+=a.nsp+",");null!=a.id&&(b+=a.id);if(null!=a.data){try{var k=JSON.stringify(a.data)}catch(m){k=!1}if(!1!==k)b+=k;else return h}v("encoded %j as %s",a,b);return b}function g(a,b){u.removeBlobs(a,function(k){var m=u.deconstructPacket(k);k=d(m.packet);m=m.buffers;m.unshift(k);b(m)})}function l(){this.reconstructor=null}function p(a){this.reconPack=a;this.buffers=[]}var v=e(3)("socket.io-parser");
n=e(8);var u=e(9),t=e(10),r=e(11);f.protocol=4;f.types="CONNECT DISCONNECT EVENT ACK ERROR BINARY_EVENT BINARY_ACK".split(" ");f.CONNECT=0;f.DISCONNECT=1;f.EVENT=2;f.ACK=3;f.ERROR=4;f.BINARY_EVENT=5;f.BINARY_ACK=6;f.Encoder=c;f.Decoder=l;var h=f.ERROR+'"encode error"';c.prototype.encode=function(a,b){v("encoding packet %j",a);f.BINARY_EVENT===a.type||f.BINARY_ACK===a.type?g(a,b):(a=d(a),b([a]))};n(l.prototype);l.prototype.add=function(a){if("string"===typeof a){a:{var b=0,k={type:Number(a.charAt(0))};
if(null==f.types[k.type])a={type:f.ERROR,data:"parser error: unknown packet type "+k.type};else{if(f.BINARY_EVENT===k.type||f.BINARY_ACK===k.type){for(var m="";"-"!==a.charAt(++b)&&(m+=a.charAt(b),b!=a.length););if(m!=Number(m)||"-"!==a.charAt(b))throw Error("Illegal attachments");k.attachments=Number(m)}if("/"===a.charAt(b+1))for(k.nsp="";++b;){m=a.charAt(b);if(","===m)break;k.nsp+=m;if(b===a.length)break}else k.nsp="/";m=a.charAt(b+1);if(""!==m&&Number(m)==m){for(k.id="";++b;){m=a.charAt(b);if(null==
m||Number(m)!=m){--b;break}k.id+=a.charAt(b);if(b===a.length)break}k.id=Number(k.id)}if(a.charAt(++b)){b=a.substr(b);try{var w=JSON.parse(b)}catch(B){w=!1}if(!1===w||k.type!==f.ERROR&&!t(w)){a={type:f.ERROR,data:"parser error: invalid payload"};break a}else k.data=w}v("decoded %s as %j",a,k);a=k}}f.BINARY_EVENT===a.type||f.BINARY_ACK===a.type?(this.reconstructor=new p(a),0===this.reconstructor.reconPack.attachments&&this.emit("decoded",a)):this.emit("decoded",a)}else if(r(a)||a.base64)if(this.reconstructor){if(a=
this.reconstructor.takeBinaryData(a))this.reconstructor=null,this.emit("decoded",a)}else throw Error("got binary data when not reconstructing a packet");else throw Error("Unknown type: "+a);};l.prototype.destroy=function(){this.reconstructor&&this.reconstructor.finishedReconstruction()};p.prototype.takeBinaryData=function(a){this.buffers.push(a);return this.buffers.length===this.reconPack.attachments?(a=u.reconstructPacket(this.reconPack,this.buffers),this.finishedReconstruction(),a):null};p.prototype.finishedReconstruction=
function(){this.reconPack=null;this.buffers=[]}},function(n,f,e){function c(d){if(d){for(var g in c.prototype)d[g]=c.prototype[g];return d}}n.exports=c;c.prototype.on=c.prototype.addEventListener=function(d,g){this._callbacks=this._callbacks||{};(this._callbacks["$"+d]=this._callbacks["$"+d]||[]).push(g);return this};c.prototype.once=function(d,g){function l(){this.off(d,l);g.apply(this,arguments)}l.fn=g;this.on(d,l);return this};c.prototype.off=c.prototype.removeListener=c.prototype.removeAllListeners=
c.prototype.removeEventListener=function(d,g){this._callbacks=this._callbacks||{};if(0==arguments.length)return this._callbacks={},this;var l=this._callbacks["$"+d];if(!l)return this;if(1==arguments.length)return delete this._callbacks["$"+d],this;for(var p,v=0;v<l.length;v++)if(p=l[v],p===g||p.fn===g){l.splice(v,1);break}return this};c.prototype.emit=function(d){this._callbacks=this._callbacks||{};var g=[].slice.call(arguments,1),l=this._callbacks["$"+d];if(l){l=l.slice(0);for(var p=0,v=l.length;p<
v;++p)l[p].apply(this,g)}return this};c.prototype.listeners=function(d){this._callbacks=this._callbacks||{};return this._callbacks["$"+d]||[]};c.prototype.hasListeners=function(d){return!!this.listeners(d).length}},function(n,f,e){(function(c){function d(r,h){if(!r)return r;if(p(r)){var a={_placeholder:!0,num:h.length};h.push(r);return a}if(l(r)){a=Array(r.length);for(var b=0;b<r.length;b++)a[b]=d(r[b],h);return a}if("object"===typeof r&&!(r instanceof Date)){a={};for(b in r)a[b]=d(r[b],h);return a}return r}
function g(r,h){if(!r)return r;if(r&&r._placeholder)return h[r.num];if(l(r))for(var a=0;a<r.length;a++)r[a]=g(r[a],h);else if("object"===typeof r)for(a in r)r[a]=g(r[a],h);return r}var l=e(10),p=e(11),v=Object.prototype.toString,u="function"===typeof c.Blob||"[object BlobConstructor]"===v.call(c.Blob),t="function"===typeof c.File||"[object FileConstructor]"===v.call(c.File);f.deconstructPacket=function(r){var h=[];r.data=d(r.data,h);r.attachments=h.length;return{packet:r,buffers:h}};f.reconstructPacket=
function(r,h){r.data=g(r.data,h);r.attachments=void 0;return r};f.removeBlobs=function(r,h){function a(m,w,B){if(!m)return m;if(u&&m instanceof Blob||t&&m instanceof File){b++;var q=new FileReader;q.onload=function(){B?B[w]=this.result:k=this.result;--b||h(k)};q.readAsArrayBuffer(m)}else if(l(m))for(q=0;q<m.length;q++)a(m[q],q,m);else if("object"===typeof m&&!p(m))for(q in m)a(m[q],q,m)}var b=0,k=r;a(k);b||h(k)}}).call(f,function(){return this}())},function(n,f){var e={}.toString;n.exports=Array.isArray||
function(c){return"[object Array]"==e.call(c)}},function(n,f){(function(e){n.exports=function(l){return c&&e.Buffer.isBuffer(l)||d&&(l instanceof e.ArrayBuffer||g(l))};var c="function"===typeof e.Buffer&&"function"===typeof e.Buffer.isBuffer,d="function"===typeof e.ArrayBuffer,g=function(){return d&&"function"===typeof e.ArrayBuffer.isView?e.ArrayBuffer.isView:function(l){return l.buffer instanceof e.ArrayBuffer}}()}).call(f,function(){return this}())},function(n,f,e){function c(b,k){if(!(this instanceof
c))return new c(b,k);b&&"object"===("undefined"===typeof b?"undefined":d(b))&&(k=b,b=void 0);k=k||{};k.path=k.path||"/socket.io";this.nsps={};this.subs=[];this.opts=k;this.reconnection(!1!==k.reconnection);this.reconnectionAttempts(k.reconnectionAttempts||Infinity);this.reconnectionDelay(k.reconnectionDelay||1E3);this.reconnectionDelayMax(k.reconnectionDelayMax||5E3);this.randomizationFactor(k.randomizationFactor||.5);this.backoff=new h({min:this.reconnectionDelay(),max:this.reconnectionDelayMax(),
jitter:this.randomizationFactor()});this.timeout(null==k.timeout?2E4:k.timeout);this.readyState="closed";this.uri=b;this.connecting=[];this.lastPing=null;this.encoding=!1;this.packetBuffer=[];var m=k.parser||p;this.encoder=new m.Encoder;this.decoder=new m.Decoder;(this.autoConnect=!1!==k.autoConnect)&&this.open()}var d="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&"function"===typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?
"symbol":typeof b},g=e(13),l=e(37);f=e(8);var p=e(7),v=e(39),u=e(40),t=e(3)("socket.io-client:manager"),r=e(36),h=e(41),a=Object.prototype.hasOwnProperty;n.exports=c;c.prototype.emitAll=function(){this.emit.apply(this,arguments);for(var b in this.nsps)a.call(this.nsps,b)&&this.nsps[b].emit.apply(this.nsps[b],arguments)};c.prototype.updateSocketIds=function(){for(var b in this.nsps)a.call(this.nsps,b)&&(this.nsps[b].id=this.generateId(b))};c.prototype.generateId=function(b){return("/"===b?"":b+"#")+
this.engine.id};f(c.prototype);c.prototype.reconnection=function(b){if(!arguments.length)return this._reconnection;this._reconnection=!!b;return this};c.prototype.reconnectionAttempts=function(b){if(!arguments.length)return this._reconnectionAttempts;this._reconnectionAttempts=b;return this};c.prototype.reconnectionDelay=function(b){if(!arguments.length)return this._reconnectionDelay;this._reconnectionDelay=b;this.backoff&&this.backoff.setMin(b);return this};c.prototype.randomizationFactor=function(b){if(!arguments.length)return this._randomizationFactor;
this._randomizationFactor=b;this.backoff&&this.backoff.setJitter(b);return this};c.prototype.reconnectionDelayMax=function(b){if(!arguments.length)return this._reconnectionDelayMax;this._reconnectionDelayMax=b;this.backoff&&this.backoff.setMax(b);return this};c.prototype.timeout=function(b){if(!arguments.length)return this._timeout;this._timeout=b;return this};c.prototype.maybeReconnectOnOpen=function(){!this.reconnecting&&this._reconnection&&0===this.backoff.attempts&&this.reconnect()};c.prototype.open=
c.prototype.connect=function(b,k){t("readyState %s",this.readyState);if(~this.readyState.indexOf("open"))return this;t("opening %s",this.uri);var m=this.engine=g(this.uri,this.opts),w=this;this.readyState="opening";this.skipReconnect=!1;var B=v(m,"open",function(){w.onopen();b&&b()});k=v(m,"error",function(y){t("connect_error");w.cleanup();w.readyState="closed";w.emitAll("connect_error",y);if(b){var z=Error("Connection error");z.data=y;b(z)}else w.maybeReconnectOnOpen()});if(!1!==this._timeout){var q=
this._timeout;t("connect attempt will timeout after %d",q);var x=setTimeout(function(){t("connect attempt timed out after %d",q);B.destroy();m.close();m.emit("error","timeout");w.emitAll("connect_timeout",q)},q);this.subs.push({destroy:function(){clearTimeout(x)}})}this.subs.push(B);this.subs.push(k);return this};c.prototype.onopen=function(){t("open");this.cleanup();this.readyState="open";this.emit("open");var b=this.engine;this.subs.push(v(b,"data",u(this,"ondata")));this.subs.push(v(b,"ping",u(this,
"onping")));this.subs.push(v(b,"pong",u(this,"onpong")));this.subs.push(v(b,"error",u(this,"onerror")));this.subs.push(v(b,"close",u(this,"onclose")));this.subs.push(v(this.decoder,"decoded",u(this,"ondecoded")))};c.prototype.onping=function(){this.lastPing=new Date;this.emitAll("ping")};c.prototype.onpong=function(){this.emitAll("pong",new Date-this.lastPing)};c.prototype.ondata=function(b){this.decoder.add(b)};c.prototype.ondecoded=function(b){this.emit("packet",b)};c.prototype.onerror=function(b){t("error",
b);this.emitAll("error",b)};c.prototype.socket=function(b,k){function m(){~r(B.connecting,w)||B.connecting.push(w)}var w=this.nsps[b];if(!w){w=new l(this,b,k);this.nsps[b]=w;var B=this;w.on("connecting",m);w.on("connect",function(){w.id=B.generateId(b)});this.autoConnect&&m()}return w};c.prototype.destroy=function(b){b=r(this.connecting,b);~b&&this.connecting.splice(b,1);this.connecting.length||this.close()};c.prototype.packet=function(b){t("writing packet %j",b);var k=this;b.query&&0===b.type&&(b.nsp+=
"?"+b.query);k.encoding?k.packetBuffer.push(b):(k.encoding=!0,this.encoder.encode(b,function(m){for(var w=0;w<m.length;w++)k.engine.write(m[w],b.options);k.encoding=!1;k.processPacketQueue()}))};c.prototype.processPacketQueue=function(){if(0<this.packetBuffer.length&&!this.encoding){var b=this.packetBuffer.shift();this.packet(b)}};c.prototype.cleanup=function(){t("cleanup");for(var b=this.subs.length,k=0;k<b;k++)this.subs.shift().destroy();this.packetBuffer=[];this.encoding=!1;this.lastPing=null;
this.decoder.destroy()};c.prototype.close=c.prototype.disconnect=function(){t("disconnect");this.skipReconnect=!0;this.reconnecting=!1;"opening"===this.readyState&&this.cleanup();this.backoff.reset();this.readyState="closed";this.engine&&this.engine.close()};c.prototype.onclose=function(b){t("onclose");this.cleanup();this.backoff.reset();this.readyState="closed";this.emit("close",b);this._reconnection&&!this.skipReconnect&&this.reconnect()};c.prototype.reconnect=function(){if(this.reconnecting||this.skipReconnect)return this;
var b=this;if(this.backoff.attempts>=this._reconnectionAttempts)t("reconnect failed"),this.backoff.reset(),this.emitAll("reconnect_failed"),this.reconnecting=!1;else{var k=this.backoff.duration();t("will wait %dms before reconnect attempt",k);this.reconnecting=!0;var m=setTimeout(function(){b.skipReconnect||(t("attempting reconnect"),b.emitAll("reconnect_attempt",b.backoff.attempts),b.emitAll("reconnecting",b.backoff.attempts),b.skipReconnect||b.open(function(w){w?(t("reconnect attempt error"),b.reconnecting=
!1,b.reconnect(),b.emitAll("reconnect_error",w.data)):(t("reconnect success"),b.onreconnect())}))},k);this.subs.push({destroy:function(){clearTimeout(m)}})}};c.prototype.onreconnect=function(){var b=this.backoff.attempts;this.reconnecting=!1;this.backoff.reset();this.updateSocketIds();this.emitAll("reconnect",b)}},function(n,f,e){n.exports=e(14);n.exports.parser=e(21)},function(n,f,e){(function(c){function d(h,a){if(!(this instanceof d))return new d(h,a);a=a||{};h&&"object"===typeof h&&(a=h,h=null);
h?(h=t(h),a.hostname=h.host,a.secure="https"===h.protocol||"wss"===h.protocol,a.port=h.port,h.query&&(a.query=h.query)):a.host&&(a.hostname=t(a.host).host);this.secure=null!=a.secure?a.secure:c.location&&"https:"===location.protocol;a.hostname&&!a.port&&(a.port=this.secure?"443":"80");this.agent=a.agent||!1;this.hostname=a.hostname||(c.location?location.hostname:"localhost");this.port=a.port||(c.location&&location.port?location.port:this.secure?443:80);this.query=a.query||{};"string"===typeof this.query&&
(this.query=r.decode(this.query));this.upgrade=!1!==a.upgrade;this.path=(a.path||"/engine.io").replace(/\/$/,"")+"/";this.forceJSONP=!!a.forceJSONP;this.jsonp=!1!==a.jsonp;this.forceBase64=!!a.forceBase64;this.enablesXDR=!!a.enablesXDR;this.timestampParam=a.timestampParam||"t";this.timestampRequests=a.timestampRequests;this.transports=a.transports||["polling","websocket"];this.transportOptions=a.transportOptions||{};this.readyState="";this.writeBuffer=[];this.prevBufferLen=0;this.policyPort=a.policyPort||
843;this.rememberUpgrade=a.rememberUpgrade||!1;this.binaryType=null;this.onlyBinaryUpgrades=a.onlyBinaryUpgrades;this.perMessageDeflate=!1!==a.perMessageDeflate?a.perMessageDeflate||{}:!1;!0===this.perMessageDeflate&&(this.perMessageDeflate={});this.perMessageDeflate&&null==this.perMessageDeflate.threshold&&(this.perMessageDeflate.threshold=1024);this.pfx=a.pfx||null;this.key=a.key||null;this.passphrase=a.passphrase||null;this.cert=a.cert||null;this.ca=a.ca||null;this.ciphers=a.ciphers||null;this.rejectUnauthorized=
void 0===a.rejectUnauthorized?!0:a.rejectUnauthorized;this.forceNode=!!a.forceNode;h="object"===typeof c&&c;h.global===h&&(a.extraHeaders&&0<Object.keys(a.extraHeaders).length&&(this.extraHeaders=a.extraHeaders),a.localAddress&&(this.localAddress=a.localAddress));this.pingTimeoutTimer=this.pingIntervalTimer=this.pingTimeout=this.pingInterval=this.upgrades=this.id=null;this.open()}var g=e(15),l=e(8),p=e(3)("engine.io-client:socket"),v=e(36),u=e(21),t=e(2),r=e(30);n.exports=d;d.priorWebsocketSuccess=
!1;l(d.prototype);d.protocol=u.protocol;d.Socket=d;d.Transport=e(20);d.transports=e(15);d.parser=e(21);d.prototype.createTransport=function(h){p('creating transport "%s"',h);var a=this.query,b={},k;for(k in a)a.hasOwnProperty(k)&&(b[k]=a[k]);b.EIO=u.protocol;b.transport=h;a=this.transportOptions[h]||{};this.id&&(b.sid=this.id);return new g[h]({query:b,socket:this,agent:a.agent||this.agent,hostname:a.hostname||this.hostname,port:a.port||this.port,secure:a.secure||this.secure,path:a.path||this.path,
forceJSONP:a.forceJSONP||this.forceJSONP,jsonp:a.jsonp||this.jsonp,forceBase64:a.forceBase64||this.forceBase64,enablesXDR:a.enablesXDR||this.enablesXDR,timestampRequests:a.timestampRequests||this.timestampRequests,timestampParam:a.timestampParam||this.timestampParam,policyPort:a.policyPort||this.policyPort,pfx:a.pfx||this.pfx,key:a.key||this.key,passphrase:a.passphrase||this.passphrase,cert:a.cert||this.cert,ca:a.ca||this.ca,ciphers:a.ciphers||this.ciphers,rejectUnauthorized:a.rejectUnauthorized||
this.rejectUnauthorized,perMessageDeflate:a.perMessageDeflate||this.perMessageDeflate,extraHeaders:a.extraHeaders||this.extraHeaders,forceNode:a.forceNode||this.forceNode,localAddress:a.localAddress||this.localAddress,requestTimeout:a.requestTimeout||this.requestTimeout,protocols:a.protocols||void 0})};d.prototype.open=function(){if(this.rememberUpgrade&&d.priorWebsocketSuccess&&-1!==this.transports.indexOf("websocket"))var h="websocket";else{if(0===this.transports.length){var a=this;setTimeout(function(){a.emit("error",
"No transports available")},0);return}h=this.transports[0]}this.readyState="opening";try{h=this.createTransport(h)}catch(b){this.transports.shift();this.open();return}h.open();this.setTransport(h)};d.prototype.setTransport=function(h){p("setting transport %s",h.name);var a=this;this.transport&&(p("clearing existing transport %s",this.transport.name),this.transport.removeAllListeners());this.transport=h;h.on("drain",function(){a.onDrain()}).on("packet",function(b){a.onPacket(b)}).on("error",function(b){a.onError(b)}).on("close",
function(){a.onClose("transport close")})};d.prototype.probe=function(h){function a(){if(z.onlyBinaryUpgrades){var A=!this.supportsBinary&&z.transport.supportsBinary;y=y||A}y||(p('probe transport "%s" opened',h),x.send([{type:"ping",data:"probe"}]),x.once("packet",function(C){y||("pong"===C.type&&"probe"===C.data?(p('probe transport "%s" pong',h),z.upgrading=!0,z.emit("upgrading",x),x&&(d.priorWebsocketSuccess="websocket"===x.name,p('pausing current transport "%s"',z.transport.name),z.transport.pause(function(){y||
"closed"===z.readyState||(p("changing transport and sending upgrade packet"),q(),z.setTransport(x),x.send([{type:"upgrade"}]),z.emit("upgrade",x),x=null,z.upgrading=!1,z.flush())}))):(p('probe transport "%s" failed',h),C=Error("probe error"),C.transport=x.name,z.emit("upgradeError",C)))}))}function b(){y||(y=!0,q(),x.close(),x=null)}function k(A){var C=Error("probe error: "+A);C.transport=x.name;b();p('probe transport "%s" failed because of error: %s',h,A);z.emit("upgradeError",C)}function m(){k("transport closed")}
function w(){k("socket closed")}function B(A){x&&A.name!==x.name&&(p('"%s" works - aborting "%s"',A.name,x.name),b())}function q(){x.removeListener("open",a);x.removeListener("error",k);x.removeListener("close",m);z.removeListener("close",w);z.removeListener("upgrading",B)}p('probing transport "%s"',h);var x=this.createTransport(h,{probe:1}),y=!1,z=this;d.priorWebsocketSuccess=!1;x.once("open",a);x.once("error",k);x.once("close",m);this.once("close",w);this.once("upgrading",B);x.open()};d.prototype.onOpen=
function(){p("socket open");this.readyState="open";d.priorWebsocketSuccess="websocket"===this.transport.name;this.emit("open");this.flush();if("open"===this.readyState&&this.upgrade&&this.transport.pause){p("starting upgrade probes");for(var h=0,a=this.upgrades.length;h<a;h++)this.probe(this.upgrades[h])}};d.prototype.onPacket=function(h){if("opening"===this.readyState||"open"===this.readyState||"closing"===this.readyState)switch(p('socket receive: type "%s", data "%s"',h.type,h.data),this.emit("packet",
h),this.emit("heartbeat"),h.type){case "open":this.onHandshake(JSON.parse(h.data));break;case "pong":this.setPing();this.emit("pong");break;case "error":var a=Error("server error");a.code=h.data;this.onError(a);break;case "message":this.emit("data",h.data),this.emit("message",h.data)}else p('packet received with socket readyState "%s"',this.readyState)};d.prototype.onHandshake=function(h){this.emit("handshake",h);this.id=h.sid;this.transport.query.sid=h.sid;this.upgrades=this.filterUpgrades(h.upgrades);
this.pingInterval=h.pingInterval;this.pingTimeout=h.pingTimeout;this.onOpen();"closed"!==this.readyState&&(this.setPing(),this.removeListener("heartbeat",this.onHeartbeat),this.on("heartbeat",this.onHeartbeat))};d.prototype.onHeartbeat=function(h){clearTimeout(this.pingTimeoutTimer);var a=this;a.pingTimeoutTimer=setTimeout(function(){if("closed"!==a.readyState)a.onClose("ping timeout")},h||a.pingInterval+a.pingTimeout)};d.prototype.setPing=function(){var h=this;clearTimeout(h.pingIntervalTimer);h.pingIntervalTimer=
setTimeout(function(){p("writing ping packet - expecting pong within %sms",h.pingTimeout);h.ping();h.onHeartbeat(h.pingTimeout)},h.pingInterval)};d.prototype.ping=function(){var h=this;this.sendPacket("ping",function(){h.emit("ping")})};d.prototype.onDrain=function(){this.writeBuffer.splice(0,this.prevBufferLen);this.prevBufferLen=0;0===this.writeBuffer.length?this.emit("drain"):this.flush()};d.prototype.flush=function(){"closed"!==this.readyState&&this.transport.writable&&!this.upgrading&&this.writeBuffer.length&&
(p("flushing %d packets in socket",this.writeBuffer.length),this.transport.send(this.writeBuffer),this.prevBufferLen=this.writeBuffer.length,this.emit("flush"))};d.prototype.write=d.prototype.send=function(h,a,b){this.sendPacket("message",h,a,b);return this};d.prototype.sendPacket=function(h,a,b,k){"function"===typeof a&&(k=a,a=void 0);"function"===typeof b&&(k=b,b=null);if("closing"!==this.readyState&&"closed"!==this.readyState){b=b||{};b.compress=!1!==b.compress;h={type:h,data:a,options:b};this.emit("packetCreate",
h);this.writeBuffer.push(h);if(k)this.once("flush",k);this.flush()}};d.prototype.close=function(){function h(){k.onClose("forced close");p("socket closing - telling transport to close");k.transport.close()}function a(){k.removeListener("upgrade",a);k.removeListener("upgradeError",a);h()}function b(){k.once("upgrade",a);k.once("upgradeError",a)}if("opening"===this.readyState||"open"===this.readyState){this.readyState="closing";var k=this;if(this.writeBuffer.length)this.once("drain",function(){this.upgrading?
b():h()});else this.upgrading?b():h()}return this};d.prototype.onError=function(h){p("socket error %j",h);d.priorWebsocketSuccess=!1;this.emit("error",h);this.onClose("transport error",h)};d.prototype.onClose=function(h,a){if("opening"===this.readyState||"open"===this.readyState||"closing"===this.readyState)p('socket close with reason: "%s"',h),clearTimeout(this.pingIntervalTimer),clearTimeout(this.pingTimeoutTimer),this.transport.removeAllListeners("close"),this.transport.close(),this.transport.removeAllListeners(),
this.readyState="closed",this.id=null,this.emit("close",h,a),this.writeBuffer=[],this.prevBufferLen=0};d.prototype.filterUpgrades=function(h){for(var a=[],b=0,k=h.length;b<k;b++)~v(this.transports,h[b])&&a.push(h[b]);return a}}).call(f,function(){return this}())},function(n,f,e){(function(c){var d=e(16),g=e(18),l=e(33),p=e(34);f.polling=function(v){var u=!1,t=!1,r=!1!==v.jsonp;c.location&&(t="https:"===location.protocol,(u=location.port)||(u=t?443:80),u=v.hostname!==location.hostname||u!==v.port,
t=v.secure!==t);v.xdomain=u;v.xscheme=t;if("open"in new d(v)&&!v.forceJSONP)return new g(v);if(!r)throw Error("JSONP disabled");return new l(v)};f.websocket=p}).call(f,function(){return this}())},function(n,f,e){(function(c){var d=e(17);n.exports=function(g){var l=g.xdomain,p=g.xscheme;g=g.enablesXDR;try{if("undefined"!==typeof XMLHttpRequest&&(!l||d))return new XMLHttpRequest}catch(v){}try{if("undefined"!==typeof XDomainRequest&&!p&&g)return new XDomainRequest}catch(v){}if(!l)try{return new (c[["Active"].concat("Object").join("X")])("Microsoft.XMLHTTP")}catch(v){}}}).call(f,
function(){return this}())},function(n,f){try{n.exports="undefined"!==typeof XMLHttpRequest&&"withCredentials"in new XMLHttpRequest}catch(e){n.exports=!1}},function(n,f,e){(function(c){function d(){}function g(a){u.call(this,a);this.requestTimeout=a.requestTimeout;this.extraHeaders=a.extraHeaders;if(c.location){var b="https:"===location.protocol,k=location.port;k||(k=b?443:80);this.xd=a.hostname!==c.location.hostname||k!==a.port;this.xs=a.secure!==b}}function l(a){this.method=a.method||"GET";this.uri=
a.uri;this.xd=!!a.xd;this.xs=!!a.xs;this.async=!1!==a.async;this.data=void 0!==a.data?a.data:null;this.agent=a.agent;this.isBinary=a.isBinary;this.supportsBinary=a.supportsBinary;this.enablesXDR=a.enablesXDR;this.requestTimeout=a.requestTimeout;this.pfx=a.pfx;this.key=a.key;this.passphrase=a.passphrase;this.cert=a.cert;this.ca=a.ca;this.ciphers=a.ciphers;this.rejectUnauthorized=a.rejectUnauthorized;this.extraHeaders=a.extraHeaders;this.create()}function p(){for(var a in l.requests)l.requests.hasOwnProperty(a)&&
l.requests[a].abort()}var v=e(16),u=e(19),t=e(8),r=e(31),h=e(3)("engine.io-client:polling-xhr");n.exports=g;n.exports.Request=l;r(g,u);g.prototype.supportsBinary=!0;g.prototype.request=function(a){a=a||{};a.uri=this.uri();a.xd=this.xd;a.xs=this.xs;a.agent=this.agent||!1;a.supportsBinary=this.supportsBinary;a.enablesXDR=this.enablesXDR;a.pfx=this.pfx;a.key=this.key;a.passphrase=this.passphrase;a.cert=this.cert;a.ca=this.ca;a.ciphers=this.ciphers;a.rejectUnauthorized=this.rejectUnauthorized;a.requestTimeout=
this.requestTimeout;a.extraHeaders=this.extraHeaders;return new l(a)};g.prototype.doWrite=function(a,b){a=this.request({method:"POST",data:a,isBinary:"string"!==typeof a&&void 0!==a});var k=this;a.on("success",b);a.on("error",function(m){k.onError("xhr post error",m)});this.sendXhr=a};g.prototype.doPoll=function(){h("xhr poll");var a=this.request(),b=this;a.on("data",function(k){b.onData(k)});a.on("error",function(k){b.onError("xhr poll error",k)});this.pollXhr=a};t(l.prototype);l.prototype.create=
function(){var a={agent:this.agent,xdomain:this.xd,xscheme:this.xs,enablesXDR:this.enablesXDR};a.pfx=this.pfx;a.key=this.key;a.passphrase=this.passphrase;a.cert=this.cert;a.ca=this.ca;a.ciphers=this.ciphers;a.rejectUnauthorized=this.rejectUnauthorized;var b=this.xhr=new v(a),k=this;try{h("xhr open %s: %s",this.method,this.uri);b.open(this.method,this.uri,this.async);try{if(this.extraHeaders){b.setDisableHeaderCheck&&b.setDisableHeaderCheck(!0);for(var m in this.extraHeaders)this.extraHeaders.hasOwnProperty(m)&&
b.setRequestHeader(m,this.extraHeaders[m])}}catch(w){}if("POST"===this.method)try{this.isBinary?b.setRequestHeader("Content-type","application/octet-stream"):b.setRequestHeader("Content-type","text/plain;charset=UTF-8")}catch(w){}try{b.setRequestHeader("Accept","*/*")}catch(w){}"withCredentials"in b&&(b.withCredentials=!0);this.requestTimeout&&(b.timeout=this.requestTimeout);this.hasXDR()?(b.onload=function(){k.onLoad()},b.onerror=function(){k.onError(b.responseText)}):b.onreadystatechange=function(){if(2===
b.readyState)try{var w=b.getResponseHeader("Content-Type");k.supportsBinary&&"application/octet-stream"===w&&(b.responseType="arraybuffer")}catch(B){}if(4===b.readyState)if(200===b.status||1223===b.status)k.onLoad();else setTimeout(function(){k.onError(b.status)},0)};h("xhr data %s",this.data);b.send(this.data)}catch(w){setTimeout(function(){k.onError(w)},0);return}c.document&&(this.index=l.requestsCount++,l.requests[this.index]=this)};l.prototype.onSuccess=function(){this.emit("success");this.cleanup()};
l.prototype.onData=function(a){this.emit("data",a);this.onSuccess()};l.prototype.onError=function(a){this.emit("error",a);this.cleanup(!0)};l.prototype.cleanup=function(a){if("undefined"!==typeof this.xhr&&null!==this.xhr){this.hasXDR()?this.xhr.onload=this.xhr.onerror=d:this.xhr.onreadystatechange=d;if(a)try{this.xhr.abort()}catch(b){}c.document&&delete l.requests[this.index];this.xhr=null}};l.prototype.onLoad=function(){try{try{var a=this.xhr.getResponseHeader("Content-Type")}catch(k){}var b="application/octet-stream"===
a?this.xhr.response||this.xhr.responseText:this.xhr.responseText}catch(k){this.onError(k)}if(null!=b)this.onData(b)};l.prototype.hasXDR=function(){return"undefined"!==typeof c.XDomainRequest&&!this.xs&&this.enablesXDR};l.prototype.abort=function(){this.cleanup()};l.requestsCount=0;l.requests={};c.document&&(c.attachEvent?c.attachEvent("onunload",p):c.addEventListener&&c.addEventListener("beforeunload",p,!1))}).call(f,function(){return this}())},function(n,f,e){function c(t){var r=t&&t.forceBase64;
if(!u||r)this.supportsBinary=!1;d.call(this,t)}var d=e(20),g=e(30),l=e(21);f=e(31);var p=e(32),v=e(3)("engine.io-client:polling");n.exports=c;var u=null!=(new (e(16))({xdomain:!1})).responseType;f(c,d);c.prototype.name="polling";c.prototype.doOpen=function(){this.poll()};c.prototype.pause=function(t){function r(){v("paused");h.readyState="paused";t()}var h=this;this.readyState="pausing";if(this.polling||!this.writable){var a=0;this.polling&&(v("we are currently polling - waiting to pause"),a++,this.once("pollComplete",
function(){v("pre-pause polling complete");--a||r()}));this.writable||(v("we are currently writing - waiting to pause"),a++,this.once("drain",function(){v("pre-pause writing complete");--a||r()}))}else r()};c.prototype.poll=function(){v("polling");this.polling=!0;this.doPoll();this.emit("poll")};c.prototype.onData=function(t){var r=this;v("polling got data %s",t);l.decodePayload(t,this.socket.binaryType,function(h,a,b){if("opening"===r.readyState)r.onOpen();if("close"===h.type)return r.onClose(),
!1;r.onPacket(h)});"closed"!==this.readyState&&(this.polling=!1,this.emit("pollComplete"),"open"===this.readyState?this.poll():v('ignoring poll - transport state "%s"',this.readyState))};c.prototype.doClose=function(){function t(){v("writing close packet");r.write([{type:"close"}])}var r=this;"open"===this.readyState?(v("transport open - closing"),t()):(v("transport not open - deferring close"),this.once("open",t))};c.prototype.write=function(t){var r=this;this.writable=!1;var h=function(){r.writable=
!0;r.emit("drain")};l.encodePayload(t,this.supportsBinary,function(a){r.doWrite(a,h)})};c.prototype.uri=function(){var t=this.query||{},r=this.secure?"https":"http",h="";!1!==this.timestampRequests&&(t[this.timestampParam]=p());this.supportsBinary||t.sid||(t.b64=1);t=g.encode(t);this.port&&("https"===r&&443!==Number(this.port)||"http"===r&&80!==Number(this.port))&&(h=":"+this.port);t.length&&(t="?"+t);var a=-1!==this.hostname.indexOf(":");return r+"://"+(a?"["+this.hostname+"]":this.hostname)+h+this.path+
t}},function(n,f,e){function c(g){this.path=g.path;this.hostname=g.hostname;this.port=g.port;this.secure=g.secure;this.query=g.query;this.timestampParam=g.timestampParam;this.timestampRequests=g.timestampRequests;this.readyState="";this.agent=g.agent||!1;this.socket=g.socket;this.enablesXDR=g.enablesXDR;this.pfx=g.pfx;this.key=g.key;this.passphrase=g.passphrase;this.cert=g.cert;this.ca=g.ca;this.ciphers=g.ciphers;this.rejectUnauthorized=g.rejectUnauthorized;this.forceNode=g.forceNode;this.extraHeaders=
g.extraHeaders;this.localAddress=g.localAddress}var d=e(21);f=e(8);n.exports=c;f(c.prototype);c.prototype.onError=function(g,l){g=Error(g);g.type="TransportError";g.description=l;this.emit("error",g);return this};c.prototype.open=function(){if("closed"===this.readyState||""===this.readyState)this.readyState="opening",this.doOpen();return this};c.prototype.close=function(){if("opening"===this.readyState||"open"===this.readyState)this.doClose(),this.onClose();return this};c.prototype.send=function(g){if("open"===
this.readyState)this.write(g);else throw Error("Transport not open");};c.prototype.onOpen=function(){this.readyState="open";this.writable=!0;this.emit("open")};c.prototype.onData=function(g){g=d.decodePacket(g,this.socket.binaryType);this.onPacket(g)};c.prototype.onPacket=function(g){this.emit("packet",g)};c.prototype.onClose=function(){this.readyState="closed";this.emit("close")}},function(n,f,e){(function(c){function d(q,x,y){if(!x)return f.encodeBase64Packet(q,y);var z=new FileReader;z.onload=
function(){q.data=z.result;f.encodePacket(q,x,!0,y)};return z.readAsArrayBuffer(q.data)}function g(q,x,y){var z=Array(q.length);y=u(q.length,y);for(var A=function(D,E,F){x(E,function(G,H){z[D]=H;F(G,z)})},C=0;C<q.length;C++)A(C,q[C],y)}var l=e(22),p=e(23),v=e(24),u=e(25),t=e(26),r;c&&c.ArrayBuffer&&(r=e(28));var h="undefined"!==typeof navigator&&/Android/i.test(navigator.userAgent),a="undefined"!==typeof navigator&&/PhantomJS/i.test(navigator.userAgent),b=h||a;f.protocol=3;var k=f.packets={open:0,
close:1,ping:2,pong:3,message:4,upgrade:5,noop:6},m=l(k),w={type:"error",data:"parser error"},B=e(29);f.encodePacket=function(q,x,y,z){"function"===typeof x&&(z=x,x=!1);"function"===typeof y&&(z=y,y=null);var A=void 0===q.data?void 0:q.data.buffer||q.data;if(c.ArrayBuffer&&A instanceof ArrayBuffer){if(x){y=q.data;x=new Uint8Array(y);y=new Uint8Array(1+y.byteLength);y[0]=k[q.type];for(q=0;q<x.length;q++)y[q+1]=x[q];q=z(y.buffer)}else q=f.encodeBase64Packet(q,z);return q}if(B&&A instanceof c.Blob)return x?
b?q=d(q,x,z):(x=new Uint8Array(1),x[0]=k[q.type],q=new B([x.buffer,q.data]),q=z(q)):q=f.encodeBase64Packet(q,z),q;if(A&&A.base64)return z("b"+f.packets[q.type]+q.data.data);x=k[q.type];void 0!==q.data&&(x+=y?t.encode(String(q.data),{strict:!1}):String(q.data));return z(""+x)};f.encodeBase64Packet=function(q,x){var y="b"+f.packets[q.type];if(B&&q.data instanceof c.Blob){var z=new FileReader;z.onload=function(){var D=z.result.split(",")[1];x(y+D)};return z.readAsDataURL(q.data)}try{var A=String.fromCharCode.apply(null,
new Uint8Array(q.data))}catch(D){q=new Uint8Array(q.data);A=Array(q.length);for(var C=0;C<q.length;C++)A[C]=q[C];A=String.fromCharCode.apply(null,A)}y+=c.btoa(A);return x(y)};f.decodePacket=function(q,x,y){if(void 0===q)return w;if("string"===typeof q){if("b"===q.charAt(0))return f.decodeBase64Packet(q.substr(1),x);if(y){a:{x=q;try{x=t.decode(x,{strict:!1})}catch(z){q=!1;break a}q=x}if(!1===q)return w}y=q.charAt(0);return Number(y)==y&&m[y]?1<q.length?{type:m[y],data:q.substring(1)}:{type:m[y]}:w}y=
(new Uint8Array(q))[0];q=v(q,1);B&&"blob"===x&&(q=new B([q]));return{type:m[y],data:q}};f.decodeBase64Packet=function(q,x){var y=m[q.charAt(0)];if(!r)return{type:y,data:{base64:!0,data:q.substr(1)}};q=r.decode(q.substr(1));"blob"===x&&B&&(q=new B([q]));return{type:y,data:q}};f.encodePayload=function(q,x,y){"function"===typeof x&&(y=x,x=null);var z=p(q);if(x&&z)return B&&!b?f.encodePayloadAsBlob(q,y):f.encodePayloadAsArrayBuffer(q,y);if(!q.length)return y("0:");g(q,function(A,C){f.encodePacket(A,z?
x:!1,!1,function(D){C(null,D.length+":"+D)})},function(A,C){return y(C.join(""))})};f.decodePayload=function(q,x,y){if("string"!==typeof q)return f.decodePayloadAsBinary(q,x,y);"function"===typeof x&&(y=x,x=null);if(""===q)return y(w,0,1);var z="";for(var A,C,D=0,E=q.length;D<E;D++)if(C=q.charAt(D),":"!==C)z+=C;else{if(""===z||z!=(A=Number(z)))return y(w,0,1);C=q.substr(D+1,A);if(z!=C.length)return y(w,0,1);if(C.length){z=f.decodePacket(C,x,!1);if(w.type===z.type&&w.data===z.data)return y(w,0,1);
if(!1===y(z,D+A,E))return}D+=A;z=""}if(""!==z)return y(w,0,1)};f.encodePayloadAsArrayBuffer=function(q,x){if(!q.length)return x(new ArrayBuffer(0));g(q,function(y,z){f.encodePacket(y,!0,!0,function(A){return z(null,A)})},function(y,z){y=z.reduce(function(D,E){E="string"===typeof E?E.length:E.byteLength;return D+E.toString().length+E+2},0);var A=new Uint8Array(y),C=0;z.forEach(function(D){var E="string"===typeof D,F=D;if(E){F=new Uint8Array(D.length);for(var G=0;G<D.length;G++)F[G]=D.charCodeAt(G);
F=F.buffer}E?A[C++]=0:A[C++]=1;D=F.byteLength.toString();for(G=0;G<D.length;G++)A[C++]=parseInt(D[G]);A[C++]=255;F=new Uint8Array(F);for(G=0;G<F.length;G++)A[C++]=F[G]});return x(A.buffer)})};f.encodePayloadAsBlob=function(q,x){g(q,function(y,z){f.encodePacket(y,!0,!0,function(A){var C=new Uint8Array(1);C[0]=1;if("string"===typeof A){for(var D=new Uint8Array(A.length),E=0;E<A.length;E++)D[E]=A.charCodeAt(E);A=D.buffer;C[0]=0}D=(A instanceof ArrayBuffer?A.byteLength:A.size).toString();var F=new Uint8Array(D.length+
1);for(E=0;E<D.length;E++)F[E]=parseInt(D[E]);F[D.length]=255;B&&(A=new B([C.buffer,F.buffer,A]),z(null,A))})},function(y,z){return x(new B(z))})};f.decodePayloadAsBinary=function(q,x,y){"function"===typeof x&&(y=x,x=null);for(var z=[];0<q.byteLength;){for(var A=new Uint8Array(q),C=0===A[0],D="",E=1;255!==A[E];E++){if(310<D.length)return y(w,0,1);D+=A[E]}q=v(q,2+D.length);D=parseInt(D);A=v(q,0,D);if(C)try{A=String.fromCharCode.apply(null,new Uint8Array(A))}catch(G){for(C=new Uint8Array(A),A="",E=
0;E<C.length;E++)A+=String.fromCharCode(C[E])}z.push(A);q=v(q,D)}var F=z.length;z.forEach(function(G,H){y(f.decodePacket(G,x,!0),H,F)})}}).call(f,function(){return this}())},function(n,f){n.exports=Object.keys||function(e){var c=[],d=Object.prototype.hasOwnProperty,g;for(g in e)d.call(e,g)&&c.push(g);return c}},function(n,f,e){(function(c){function d(u){if(!u||"object"!==typeof u)return!1;if(g(u)){for(var t=0,r=u.length;t<r;t++)if(d(u[t]))return!0;return!1}if("function"===typeof c.Buffer&&c.Buffer.isBuffer&&
c.Buffer.isBuffer(u)||"function"===typeof c.ArrayBuffer&&u instanceof ArrayBuffer||p&&u instanceof Blob||v&&u instanceof File)return!0;if(u.toJSON&&"function"===typeof u.toJSON&&1===arguments.length)return d(u.toJSON(),!0);for(t in u)if(Object.prototype.hasOwnProperty.call(u,t)&&d(u[t]))return!0;return!1}var g=e(10),l=Object.prototype.toString,p="function"===typeof c.Blob||"[object BlobConstructor]"===l.call(c.Blob),v="function"===typeof c.File||"[object FileConstructor]"===l.call(c.File);n.exports=
d}).call(f,function(){return this}())},function(n,f){n.exports=function(e,c,d){var g=e.byteLength;c=c||0;d=d||g;if(e.slice)return e.slice(c,d);0>c&&(c+=g);0>d&&(d+=g);d>g&&(d=g);if(c>=g||c>=d||0===g)return new ArrayBuffer(0);e=new Uint8Array(e);g=new Uint8Array(d-c);for(var l=0;c<d;c++,l++)g[l]=e[c];return g.buffer}},function(n,f){function e(){}n.exports=function(c,d,g){function l(v,u){if(0>=l.count)throw Error("after called too many times");--l.count;v?(p=!0,d(v),d=g):0!==l.count||p||d(null,u)}var p=
!1;g=g||e;l.count=c;return 0===c?d():l}},function(n,f,e){var c;(function(d,g){(function(l){function p(k){for(var m=[],w=0,B=k.length,q,x;w<B;)q=k.charCodeAt(w++),55296<=q&&56319>=q&&w<B?(x=k.charCodeAt(w++),56320==(x&64512)?m.push(((q&1023)<<10)+(x&1023)+65536):(m.push(q),w--)):m.push(q);return m}function v(k,m){if(55296<=k&&57343>=k){if(m)throw Error("Lone surrogate U+"+k.toString(16).toUpperCase()+" is not a scalar value");return!1}return!0}function u(){if(b>=a)throw Error("Invalid byte index");
var k=h[b]&255;b++;if(128==(k&192))return k&63;throw Error("Invalid continuation byte");}function t(k){if(b>a)throw Error("Invalid byte index");if(b==a)return!1;var m=h[b]&255;b++;if(0==(m&128))return m;if(192==(m&224)){var w=u();m=(m&31)<<6|w;if(128<=m)return m;throw Error("Invalid continuation byte");}if(224==(m&240)){w=u();var B=u();m=(m&15)<<12|w<<6|B;if(2048<=m)return v(m,k)?m:65533;throw Error("Invalid continuation byte");}if(240==(m&248)&&(w=u(),B=u(),k=u(),m=(m&7)<<18|w<<12|B<<6|k,65536<=
m&&1114111>=m))return m;throw Error("Invalid UTF-8 detected");}var r=String.fromCharCode,h,a,b;!(c={version:"2.1.2",encode:function(k,m){m=m||{};m=!1!==m.strict;k=p(k);for(var w=k.length,B=-1,q,x="";++B<w;){q=k[B];var y=m;if(0==(q&4294967168))q=r(q);else{var z="";0==(q&4294965248)?z=r(q>>6&31|192):0==(q&4294901760)?(v(q,y)||(q=65533),z=r(q>>12&15|224),z+=r(q>>6&63|128)):0==(q&4292870144)&&(z=r(q>>18&7|240),z+=r(q>>12&63|128),z+=r(q>>6&63|128));q=z+=r(q&63|128)}x+=q}return x},decode:function(k,m){m=
m||{};m=!1!==m.strict;h=p(k);a=h.length;b=0;k=[];for(var w;!1!==(w=t(m));)k.push(w);m=k.length;w=-1;for(var B,q="";++w<m;)B=k[w],65535<B&&(B-=65536,q+=r(B>>>10&1023|55296),B=56320|B&1023),q+=r(B);return q}},void 0!==c&&(d.exports=c))})(this)}).call(f,e(27)(n),function(){return this}())},function(n,f){n.exports=function(e){e.webpackPolyfill||(e.deprecate=function(){},e.paths=[],e.children=[],e.webpackPolyfill=1);return e}},function(n,f){(function(){for(var e=new Uint8Array(256),c=0;64>c;c++)e["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(c)]=
c;f.encode=function(d){d=new Uint8Array(d);var g,l=d.length,p="";for(g=0;g<l;g+=3)p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[d[g]>>2],p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(d[g]&3)<<4|d[g+1]>>4],p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(d[g+1]&15)<<2|d[g+2]>>6],p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[d[g+2]&63];2===l%3?p=p.substring(0,p.length-1)+"=":1===l%3&&(p=p.substring(0,p.length-
2)+"==");return p};f.decode=function(d){var g=.75*d.length,l=d.length,p=0;"="===d[d.length-1]&&(g--,"="===d[d.length-2]&&g--);var v=new ArrayBuffer(g),u=new Uint8Array(v);for(g=0;g<l;g+=4){var t=e[d.charCodeAt(g)];var r=e[d.charCodeAt(g+1)];var h=e[d.charCodeAt(g+2)];var a=e[d.charCodeAt(g+3)];u[p++]=t<<2|r>>4;u[p++]=(r&15)<<4|h>>2;u[p++]=(h&3)<<6|a&63}return v}})()},function(n,f){(function(e){function c(t){for(var r=0;r<t.length;r++){var h=t[r];if(h.buffer instanceof ArrayBuffer){var a=h.buffer;
if(h.byteLength!==a.byteLength){var b=new Uint8Array(h.byteLength);b.set(new Uint8Array(a,h.byteOffset,h.byteLength));a=b.buffer}t[r]=a}}}function d(t,r){r=r||{};var h=new l;c(t);for(var a=0;a<t.length;a++)h.append(t[a]);return r.type?h.getBlob(r.type):h.getBlob()}function g(t,r){c(t);return new Blob(t,r||{})}var l=e.BlobBuilder||e.WebKitBlobBuilder||e.MSBlobBuilder||e.MozBlobBuilder;try{var p=2===(new Blob(["hi"])).size}catch(t){p=!1}var v;if(v=p)try{v=2===(new Blob([new Uint8Array([1,2])])).size}catch(t){v=
!1}var u=l&&l.prototype.append&&l.prototype.getBlob;e=p?v?e.Blob:g:u?d:void 0;n.exports=e}).call(f,function(){return this}())},function(n,f){f.encode=function(e){var c="",d;for(d in e)e.hasOwnProperty(d)&&(c.length&&(c+="&"),c+=encodeURIComponent(d)+"="+encodeURIComponent(e[d]));return c};f.decode=function(e){var c={};e=e.split("&");for(var d=0,g=e.length;d<g;d++){var l=e[d].split("=");c[decodeURIComponent(l[0])]=decodeURIComponent(l[1])}return c}},function(n,f){n.exports=function(e,c){var d=function(){};
d.prototype=c.prototype;e.prototype=new d;e.prototype.constructor=e}},function(n,f){function e(u){var t="";do t=d[u%64]+t,u=Math.floor(u/64);while(0<u);return t}function c(){var u=e(+new Date);return u!==v?(l=0,v=u):u+"."+e(l++)}for(var d="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_".split(""),g={},l=0,p=0,v;64>p;p++)g[d[p]]=p;c.encode=e;c.decode=function(u){var t=0;for(p=0;p<u.length;p++)t=64*t+g[u.charAt(p)];return t};n.exports=c},function(n,f,e){(function(c){function d(){}
function g(r){l.call(this,r);this.query=this.query||{};t||(c.___eio||(c.___eio=[]),t=c.___eio);this.index=t.length;var h=this;t.push(function(a){h.onData(a)});this.query.j=this.index;c.document&&c.addEventListener&&c.addEventListener("beforeunload",function(){h.script&&(h.script.onerror=d)},!1)}var l=e(19),p=e(31);n.exports=g;var v=/\n/g,u=/\\n/g,t;p(g,l);g.prototype.supportsBinary=!1;g.prototype.doClose=function(){this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);this.form&&
(this.form.parentNode.removeChild(this.form),this.iframe=this.form=null);l.prototype.doClose.call(this)};g.prototype.doPoll=function(){var r=this,h=document.createElement("script");this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);h.async=!0;h.src=this.uri();h.onerror=function(b){r.onError("jsonp poll error",b)};var a=document.getElementsByTagName("script")[0];a?a.parentNode.insertBefore(h,a):(document.head||document.body).appendChild(h);this.script=h;"undefined"!==typeof navigator&&
/gecko/i.test(navigator.userAgent)&&setTimeout(function(){var b=document.createElement("iframe");document.body.appendChild(b);document.body.removeChild(b)},100)};g.prototype.doWrite=function(r,h){function a(){b();h()}function b(){if(k.iframe)try{k.form.removeChild(k.iframe)}catch(x){k.onError("jsonp polling iframe removal error",x)}try{q=document.createElement('<iframe src="javascript:0" name="'+k.iframeId+'">')}catch(x){q=document.createElement("iframe"),q.name=k.iframeId,q.src="javascript:0"}q.id=
k.iframeId;k.form.appendChild(q);k.iframe=q}var k=this;if(!this.form){var m=document.createElement("form"),w=document.createElement("textarea"),B=this.iframeId="eio_iframe_"+this.index,q;m.className="socketio";m.style.position="absolute";m.style.top="-1000px";m.style.left="-1000px";m.target=B;m.method="POST";m.setAttribute("accept-charset","utf-8");w.name="d";m.appendChild(w);document.body.appendChild(m);this.form=m;this.area=w}this.form.action=this.uri();b();r=r.replace(u,"\\\n");this.area.value=
r.replace(v,"\\n");try{this.form.submit()}catch(x){}this.iframe.attachEvent?this.iframe.onreadystatechange=function(){"complete"===k.iframe.readyState&&a()}:this.iframe.onload=a}}).call(f,function(){return this}())},function(n,f,e){(function(c){function d(b){b&&b.forceBase64&&(this.supportsBinary=!1);this.perMessageDeflate=b.perMessageDeflate;this.usingBrowserWebSocket=r&&!b.forceNode;this.protocols=b.protocols;this.usingBrowserWebSocket||(a=h);g.call(this,b)}var g=e(20),l=e(21),p=e(30),v=e(31),u=
e(32),t=e(3)("engine.io-client:websocket"),r=c.WebSocket||c.MozWebSocket;if("undefined"===typeof window)try{var h=e(35)}catch(b){}var a=r;a||"undefined"!==typeof window||(a=h);n.exports=d;v(d,g);d.prototype.name="websocket";d.prototype.supportsBinary=!0;d.prototype.doOpen=function(){if(this.check()){var b=this.uri(),k=this.protocols,m={agent:this.agent,perMessageDeflate:this.perMessageDeflate};m.pfx=this.pfx;m.key=this.key;m.passphrase=this.passphrase;m.cert=this.cert;m.ca=this.ca;m.ciphers=this.ciphers;
m.rejectUnauthorized=this.rejectUnauthorized;this.extraHeaders&&(m.headers=this.extraHeaders);this.localAddress&&(m.localAddress=this.localAddress);try{this.ws=this.usingBrowserWebSocket?k?new a(b,k):new a(b):new a(b,k,m)}catch(w){return this.emit("error",w)}void 0===this.ws.binaryType&&(this.supportsBinary=!1);this.ws.supports&&this.ws.supports.binary?(this.supportsBinary=!0,this.ws.binaryType="nodebuffer"):this.ws.binaryType="arraybuffer";this.addEventListeners()}};d.prototype.addEventListeners=
function(){var b=this;this.ws.onopen=function(){b.onOpen()};this.ws.onclose=function(){b.onClose()};this.ws.onmessage=function(k){b.onData(k.data)};this.ws.onerror=function(k){b.onError("websocket error",k)}};d.prototype.write=function(b){function k(){m.emit("flush");setTimeout(function(){m.writable=!0;m.emit("drain")},0)}var m=this;this.writable=!1;for(var w=b.length,B=0,q=w;B<q;B++)(function(x){l.encodePacket(x,m.supportsBinary,function(y){if(!m.usingBrowserWebSocket){var z={};x.options&&(z.compress=
x.options.compress);m.perMessageDeflate&&("string"===typeof y?c.Buffer.byteLength(y):y.length)<m.perMessageDeflate.threshold&&(z.compress=!1)}try{m.usingBrowserWebSocket?m.ws.send(y):m.ws.send(y,z)}catch(A){t("websocket closed before onclose event")}--w||k()})})(b[B])};d.prototype.onClose=function(){g.prototype.onClose.call(this)};d.prototype.doClose=function(){"undefined"!==typeof this.ws&&this.ws.close()};d.prototype.uri=function(){var b=this.query||{},k=this.secure?"wss":"ws",m="";this.port&&("wss"===
k&&443!==Number(this.port)||"ws"===k&&80!==Number(this.port))&&(m=":"+this.port);this.timestampRequests&&(b[this.timestampParam]=u());this.supportsBinary||(b.b64=1);b=p.encode(b);b.length&&(b="?"+b);var w=-1!==this.hostname.indexOf(":");return k+"://"+(w?"["+this.hostname+"]":this.hostname)+m+this.path+b};d.prototype.check=function(){return!!a&&!("__initialize"in a&&this.name===d.prototype.name)}}).call(f,function(){return this}())},function(n,f){},function(n,f){var e=[].indexOf;n.exports=function(c,
d){if(e)return c.indexOf(d);for(var g=0;g<c.length;++g)if(c[g]===d)return g;return-1}},function(n,f,e){function c(b,k,m){this.io=b;this.nsp=k;this.json=this;this.ids=0;this.acks={};this.receiveBuffer=[];this.sendBuffer=[];this.connected=!1;this.disconnected=!0;this.flags={};m&&m.query&&(this.query=m.query);this.io.autoConnect&&this.open()}var d="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&"function"===typeof Symbol&&b.constructor===
Symbol&&b!==Symbol.prototype?"symbol":typeof b},g=e(7);f=e(8);var l=e(38),p=e(39),v=e(40),u=e(3)("socket.io-client:socket"),t=e(30),r=e(23);n.exports=c;var h={connect:1,connect_error:1,connect_timeout:1,connecting:1,disconnect:1,error:1,reconnect:1,reconnect_attempt:1,reconnect_failed:1,reconnect_error:1,reconnecting:1,ping:1,pong:1},a=f.prototype.emit;f(c.prototype);c.prototype.subEvents=function(){if(!this.subs){var b=this.io;this.subs=[p(b,"open",v(this,"onopen")),p(b,"packet",v(this,"onpacket")),
p(b,"close",v(this,"onclose"))]}};c.prototype.open=c.prototype.connect=function(){if(this.connected)return this;this.subEvents();this.io.open();if("open"===this.io.readyState)this.onopen();this.emit("connecting");return this};c.prototype.send=function(){var b=l(arguments);b.unshift("message");this.emit.apply(this,b);return this};c.prototype.emit=function(b){if(h.hasOwnProperty(b))return a.apply(this,arguments),this;var k=l(arguments),m={type:(void 0!==this.flags.binary?this.flags.binary:r(k))?g.BINARY_EVENT:
g.EVENT,data:k,options:{}};m.options.compress=!this.flags||!1!==this.flags.compress;"function"===typeof k[k.length-1]&&(u("emitting packet with ack id %d",this.ids),this.acks[this.ids]=k.pop(),m.id=this.ids++);this.connected?this.packet(m):this.sendBuffer.push(m);this.flags={};return this};c.prototype.packet=function(b){b.nsp=this.nsp;this.io.packet(b)};c.prototype.onopen=function(){u("transport is open - connecting");if("/"!==this.nsp)if(this.query){var b="object"===d(this.query)?t.encode(this.query):
this.query;u("sending connect packet with query %s",b);this.packet({type:g.CONNECT,query:b})}else this.packet({type:g.CONNECT})};c.prototype.onclose=function(b){u("close (%s)",b);this.connected=!1;this.disconnected=!0;delete this.id;this.emit("disconnect",b)};c.prototype.onpacket=function(b){var k=b.type===g.ERROR&&"/"===b.nsp;if(b.nsp===this.nsp||k)switch(b.type){case g.CONNECT:this.onconnect();break;case g.EVENT:this.onevent(b);break;case g.BINARY_EVENT:this.onevent(b);break;case g.ACK:this.onack(b);
break;case g.BINARY_ACK:this.onack(b);break;case g.DISCONNECT:this.ondisconnect();break;case g.ERROR:this.emit("error",b.data)}};c.prototype.onevent=function(b){var k=b.data||[];u("emitting event %j",k);null!=b.id&&(u("attaching ack callback to event"),k.push(this.ack(b.id)));this.connected?a.apply(this,k):this.receiveBuffer.push(k)};c.prototype.ack=function(b){var k=this,m=!1;return function(){if(!m){m=!0;var w=l(arguments);u("sending ack %j",w);k.packet({type:r(w)?g.BINARY_ACK:g.ACK,id:b,data:w})}}};
c.prototype.onack=function(b){var k=this.acks[b.id];"function"===typeof k?(u("calling ack %s with %j",b.id,b.data),k.apply(this,b.data),delete this.acks[b.id]):u("bad ack %s",b.id)};c.prototype.onconnect=function(){this.connected=!0;this.disconnected=!1;this.emit("connect");this.emitBuffered()};c.prototype.emitBuffered=function(){var b;for(b=0;b<this.receiveBuffer.length;b++)a.apply(this,this.receiveBuffer[b]);this.receiveBuffer=[];for(b=0;b<this.sendBuffer.length;b++)this.packet(this.sendBuffer[b]);
this.sendBuffer=[]};c.prototype.ondisconnect=function(){u("server disconnect (%s)",this.nsp);this.destroy();this.onclose("io server disconnect")};c.prototype.destroy=function(){if(this.subs){for(var b=0;b<this.subs.length;b++)this.subs[b].destroy();this.subs=null}this.io.destroy(this)};c.prototype.close=c.prototype.disconnect=function(){this.connected&&(u("performing disconnect (%s)",this.nsp),this.packet({type:g.DISCONNECT}));this.destroy();if(this.connected)this.onclose("io client disconnect");
return this};c.prototype.compress=function(b){this.flags.compress=b;return this};c.prototype.binary=function(b){this.flags.binary=b;return this}},function(n,f){n.exports=function(e,c){for(var d=[],g=(c=c||0)||0;g<e.length;g++)d[g-c]=e[g];return d}},function(n,f){n.exports=function(e,c,d){e.on(c,d);return{destroy:function(){e.removeListener(c,d)}}}},function(n,f){var e=[].slice;n.exports=function(c,d){"string"==typeof d&&(d=c[d]);if("function"!=typeof d)throw Error("bind() requires a function");var g=
e.call(arguments,2);return function(){return d.apply(c,g.concat(e.call(arguments)))}}},function(n,f){function e(c){c=c||{};this.ms=c.min||100;this.max=c.max||1E4;this.factor=c.factor||2;this.jitter=0<c.jitter&&1>=c.jitter?c.jitter:0;this.attempts=0}n.exports=e;e.prototype.duration=function(){var c=this.ms*Math.pow(this.factor,this.attempts++);if(this.jitter){var d=Math.random(),g=Math.floor(d*this.jitter*c);c=0==(Math.floor(10*d)&1)?c-g:c+g}return Math.min(c,this.max)|0};e.prototype.reset=function(){this.attempts=
0};e.prototype.setMin=function(c){this.ms=c};e.prototype.setMax=function(c){this.max=c};e.prototype.setJitter=function(c){this.jitter=c}}])});var module$exports$google3$research$colab$oldui$static$js$ga={};(function(n,f,e,c,d,g,l){n.GoogleAnalyticsObject=d;n[d]=n[d]||function(){(n[d].q=n[d].q||[]).push(arguments)};n[d].l=1*new Date;g=f.createElement(e);l=f.getElementsByTagName(e)[0];g.async=1;g.src=c;l.parentNode.insertBefore(g,l)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");
