/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var p=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},aa=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},t=aa(this),u=function(a,b){if(b)a:{var c=t;a=a.split(".");for(var g=0;g<a.length-1;g++){var e=a[g];if(!(e in c))break a;c=c[e]}a=a[a.length-1];g=c[a];b=b(g);b!=g&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}};
u("Symbol",function(a){if(a)return a;var b=function(l,d){this.g=l;q(this,"description",{configurable:!0,writable:!0,value:d})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",g=0,e=function(l){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(l||"")+"_"+g++,l)};return e});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var g=t[b[c]];"function"===typeof g&&"function"!=typeof g.prototype[a]&&q(g.prototype,a,{configurable:!0,writable:!0,value:function(){return ba(p(this))}})}return a});
var ba=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},v=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:p(a)}},ca="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},w;
if("function"==typeof Object.setPrototypeOf)w=Object.setPrototypeOf;else{var x;a:{var da={a:!0},y={};try{y.__proto__=da;x=y.a;break a}catch(a){}x=!1}w=x?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var z=w,A=function(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(z)z(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(b,c);g&&Object.defineProperty(a,c,g)}else a[c]=b[c];a.na=b.prototype};
u("Promise",function(a){function b(){this.g=null}function c(d){return d instanceof e?d:new e(function(f){f(d)})}if(a)return a;b.prototype.i=function(d){if(null==this.g){this.g=[];var f=this;this.j(function(){f.s()})}this.g.push(d)};var g=t.setTimeout;b.prototype.j=function(d){g(d,0)};b.prototype.s=function(){for(;this.g&&this.g.length;){var d=this.g;this.g=[];for(var f=0;f<d.length;++f){var h=d[f];d[f]=null;try{h()}catch(k){this.o(k)}}}this.g=null};b.prototype.o=function(d){this.j(function(){throw d;
})};var e=function(d){this.i=0;this.j=void 0;this.g=[];this.O=!1;var f=this.o();try{d(f.resolve,f.reject)}catch(h){f.reject(h)}};e.prototype.o=function(){function d(k){return function(m){h||(h=!0,k.call(f,m))}}var f=this,h=!1;return{resolve:d(this.W),reject:d(this.s)}};e.prototype.W=function(d){if(d===this)this.s(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof e)this.ka(d);else{a:switch(typeof d){case "object":var f=null!=d;break a;case "function":f=!0;break a;default:f=
!1}f?this.V(d):this.N(d)}};e.prototype.V=function(d){var f=void 0;try{f=d.then}catch(h){this.s(h);return}"function"==typeof f?this.ma(f,d):this.N(d)};e.prototype.s=function(d){this.H(2,d)};e.prototype.N=function(d){this.H(1,d)};e.prototype.H=function(d,f){if(0!=this.i)throw Error("Cannot settle("+d+", "+f+"): Promise already settled in state"+this.i);this.i=d;this.j=f;2===this.i&&this.ha();this.T()};e.prototype.ha=function(){var d=this;g(function(){if(d.U()){var f=t.console;"undefined"!==typeof f&&
f.error(d.j)}},1)};e.prototype.U=function(){if(this.O)return!1;var d=t.CustomEvent,f=t.Event,h=t.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):"function"===typeof f?d=new f("unhandledrejection",{cancelable:!0}):(d=t.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.j;return h(d)};e.prototype.T=function(){if(null!=this.g){for(var d=0;d<this.g.length;++d)l.i(this.g[d]);
this.g=null}};var l=new b;e.prototype.ka=function(d){var f=this.o();d.u(f.resolve,f.reject)};e.prototype.ma=function(d,f){var h=this.o();try{d.call(f,h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.then=function(d,f){function h(n,r){return"function"==typeof n?function(I){try{k(n(I))}catch(J){m(J)}}:r}var k,m,K=new e(function(n,r){k=n;m=r});this.u(h(d,k),h(f,m));return K};e.prototype.catch=function(d){return this.then(void 0,d)};e.prototype.u=function(d,f){function h(){switch(k.i){case 1:d(k.j);
break;case 2:f(k.j);break;default:throw Error("Unexpected state: "+k.i);}}var k=this;null==this.g?l.i(h):this.g.push(h);this.O=!0};e.resolve=c;e.reject=function(d){return new e(function(f,h){h(d)})};e.race=function(d){return new e(function(f,h){for(var k=v(d),m=k.next();!m.done;m=k.next())c(m.value).u(f,h)})};e.all=function(d){var f=v(d),h=f.next();return h.done?c([]):new e(function(k,m){function K(I){return function(J){n[I]=J;r--;0==r&&k(n)}}var n=[],r=0;do n.push(void 0),r++,c(h.value).u(K(n.length-
1),m),h=f.next();while(!h.done)})};return e});var ea=function(a,b){a instanceof String&&(a+="");var c=0,g=!1,e={next:function(){if(!g&&c<a.length){var l=c++;return{value:b(l,a[l]),done:!1}}g=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};u("Array.prototype.entries",function(a){return a?a:function(){return ea(this,function(b,c){return[b,c]})}});
var B=this||self,C=function(a,b){function c(){}c.prototype=b.prototype;a.na=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.oa=function(g,e,l){for(var d=Array(arguments.length-2),f=2;f<arguments.length;f++)d[f-2]=arguments[f];return b.prototype[e].apply(g,d)}},D=function(a){return a};var E=function(a){this.g=a};function F(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,F);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}C(F,Error);F.prototype.name="CustomError";function G(a,b){a=a.split("%s");for(var c="",g=a.length-1,e=0;e<g;e++)c+=a[e]+(e<b.length?b[e]:"%s");F.call(this,c+a[g])}C(G,F);G.prototype.name="AssertionError";var H=function(a,b,c){if(!a){var g="Assertion failed";if(b){g+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new G(""+g,e||[]);}},L=function(a,b){throw new G("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var M=function(a,b){this.g=a;this.i=b||null};A(M,E);M.prototype.then=function(a,b,c){var g;a&&(g=fa(this,a));this.g.aa(g,b,c)};var fa=function(a,b){var c=a.i;return c?function(g){b.call(this,new c(g))}:b};var ha=[];var N=function(a){this.g=a||gbar.a;this.i=null};A(N,E);var ia=function(){H(!Object.isSealed(N),"Cannot use getInstance() with a sealed constructor.");var a="v";if(N.v&&N.hasOwnProperty(a))a=N.v;else{ha.push(N);var b=new N;N.v=b;H(N.hasOwnProperty(a),"Could not instantiate singleton.");a=b}a.i||(a.i=new M(a.g.bh()));return a.i};var O=function(a,b){this.name=a;this.value=b};O.prototype.toString=function(){return this.name};
var ja=new O("OFF",Infinity),ka=new O("WARNING",900),la=new O("CONFIG",700),ma=function(){},na,oa=function(){},pa=function(a,b){this.g=null;this.o=[];this.i=(void 0===b?null:b)||null;this.j=[];this.s={g:function(){return a}}},qa=function(a){if(a.g)return a.g;if(a.i)return qa(a.i);L("Root logger has no level set.");return ja},ra=function(a){for(var b=new oa;a;)a.o.forEach(function(c){c(b)}),a=a.i},sa=function(){this.entries={};var a=new pa("");a.g=la;this.entries[""]=a},P,Q=function(a,b){var c=a.entries[b];
if(c)return c;c=Q(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var g=new pa(b,c);a.entries[b]=g;c.j.push(g);return g},R=function(){P||(P=new sa);return P};/*

 SPDX-License-Identifier: Apache-2.0
*/
var S;var U=function(a,b){this.g=a===T&&b||"";this.i=ta};U.prototype.toString=function(){return"Const{"+this.g+"}"};var ua=function(a){if(a instanceof U&&a.constructor===U&&a.i===ta)return a.g;L("expected object of type Const, got '"+a+"'");return"type_error:Const"},ta={},T={};var V=function(a,b){this.g=b===va?a:""};V.prototype.toString=function(){return this.g+""};var va={},wa=function(a){if(void 0===S){var b=null;var c=B.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:D,createScript:D,createScriptURL:D})}catch(g){B.console&&B.console.error(g.message)}S=b}else S=b}a=(b=S)?b.createScriptURL(a):a;return new V(a,va)};var xa=[],ya=function(a){var b;if(b=Q(R(),"safevalues").s){a="A URL with content '"+a+"' was sanitized away.";var c;if(c=b)if(c=b&&ka){c=ka.value;var g=b?qa(Q(R(),b.g())):ja;c=c>=g.value}c&&(b=Q(R(),b.g()),"function"===typeof a&&a(),na||(na=new ma),ra(b))}};-1===xa.indexOf(ya)&&xa.push(ya);function za(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");W?(Aa=!0,Ba&&X()):X()}var X,Y=null,Z=window,W=Z.colabExperiments&&Z.colabExperiments.gis_auth,Ba=!1,Aa=!1,Ca=document.getElementsByTagName("script")[0];
function Da(){if(Y)return Y;window.performance.mark("gapi_load_start");var a=Z.colabExperiments&&Z.colabExperiments.first_party_auth;return a&&"undefined"!==typeof gbar?Y=(new Promise(function(b){ia().then(function(){b()})})).then(function(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");return new Promise(function(b){W?gapi.load("client",b):gapi.load("auth:client",b)})}):Y=new Promise(function(b,c){X=b;Z.gapi_onload=function(){a?
X():W?gapi.load("client",za):gapi.load("auth:client",za)};var g=wa(ua(new U(T,"https://apis.google.com/js/client.js")));Ea({src:g,onerror:function(){c(Error("Error loading "+g))}});if(W&&!a){var e=wa(ua(new U(T,"https://accounts.google.com/gsi/client")));Ea({src:e,onload:function(){Ba=!0;Aa&&X()},onerror:function(){c(Error("Error loading "+e))}})}})}
function Ea(a){var b=document;var c="SCRIPT";"application/xhtml+xml"===b.contentType&&(c=c.toLowerCase());c=b.createElement(c);b=a.src;if(b instanceof V&&b.constructor===V)b=b.g;else{var g=typeof b;L("expected object of type TrustedResourceUrl, got '"+b+"' of type "+("object"!=g?g:b?Array.isArray(b)?"array":g:"null"));b="type_error:TrustedResourceUrl"}c.src=b;var e,l;(e=(b=null==(l=(e=(c.ownerDocument&&c.ownerDocument.defaultView||window).document).querySelector)?void 0:l.call(e,"script[nonce]"))?
b.nonce||b.getAttribute("nonce")||"":"")&&c.setAttribute("nonce",e);c.async=!0;a.onload&&(c.onload=a.onload);a.onerror&&(c.onerror=a.onerror);Ca.parentNode.insertBefore(c,Ca)}Z.colab_gapi_loader={load:Da};Da().then(function(){},function(){});
